version: '3'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    command: pytest
